-- MVP control structures kept in dwh for a single-schema demo setup.
-- These objects are intentionally lightweight and store current status
-- for one process and one business date.

CREATE TABLE dwh.ctl_process_run (
  process_run_id      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  process_name        VARCHAR2(100 CHAR)  NOT NULL,
  business_date       DATE                NOT NULL,
  run_mode            VARCHAR2(10 CHAR)   DEFAULT 'AUTO' NOT NULL,
  status              VARCHAR2(20 CHAR)   DEFAULT 'WAITING' NOT NULL,
  reason_code         VARCHAR2(100 CHAR),
  retry_count         NUMBER(5)           DEFAULT 0 NOT NULL,
  scheduled_for_ts    TIMESTAMP,
  next_retry_ts       TIMESTAMP,
  started_ts          TIMESTAMP,
  finished_ts         TIMESTAMP,
  expected_row_count  NUMBER(12),
  stage_row_count     NUMBER(12)          DEFAULT 0 NOT NULL,
  reject_row_count    NUMBER(12)          DEFAULT 0 NOT NULL,
  core_row_count      NUMBER(12)          DEFAULT 0 NOT NULL,
  data_file_name      VARCHAR2(255 CHAR),
  ready_file_name     VARCHAR2(255 CHAR),
  status_message      VARCHAR2(4000 CHAR),
  created_ts          TIMESTAMP           DEFAULT SYSTIMESTAMP NOT NULL,
  updated_ts          TIMESTAMP           DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT pk_ctl_process_run PRIMARY KEY (process_run_id),
  CONSTRAINT uq_ctl_process_run UNIQUE (process_name, business_date),
  CONSTRAINT chk_ctl_process_run_mode
    CHECK (run_mode IN ('AUTO', 'MANUAL')),
  CONSTRAINT chk_ctl_process_run_status
    CHECK (status IN ('WAITING', 'PROCESSING', 'DONE', 'WARNING', 'FAILED')),
  CONSTRAINT chk_ctl_process_run_retry
    CHECK (retry_count >= 0),
  CONSTRAINT chk_ctl_process_run_expected
    CHECK (expected_row_count IS NULL OR expected_row_count >= 0),
  CONSTRAINT chk_ctl_process_run_stage
    CHECK (stage_row_count >= 0),
  CONSTRAINT chk_ctl_process_run_reject
    CHECK (reject_row_count >= 0),
  CONSTRAINT chk_ctl_process_run_core
    CHECK (core_row_count >= 0)
);
